import turtle
turtle.pen()

turtle.forward(75)
turtle.left(45)
turtle.penup()
turtle.forward(75)
turtle.left(45)
turtle.pendown()
turtle.forward(75)
turtle.left(45)
turtle.penup()
turtle.forward(75)
turtle.left(45)
turtle.pendown()
turtle.forward(75)
turtle.left(45)
turtle.penup()
turtle.forward(75)
turtle.left(45)
turtle.pendown()
turtle.forward(75)
turtle.left(45)
turtle.penup()
turtle.forward(75)
turtle.left(45)
turtle.pendown()

input("Press enter in the terminal to exit. ")